title: ESDC Security Knowledge Portal
description: The Employment and Social Development Canada Security informational site on best practices and helpful resources for developers and Security Champions.

plugins:
  - jemoji

include:
  - _pages

exclude: [node_modules, .gitignore, .markdown-link-check.json, .makrdownlink.json, .travis.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, link-check.js, package-lock.json, package.json, README.md, SECURITY.md]

collections:
  references:
    output: true
  guides:
    output: true
  recommendations:
    output: true
